name: API documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install --yes doxygen
      - run: cmake -S . -B build-docs -DBNO085_BUILD_TESTS=OFF -DBNO085_BUILD_DOCS=ON
      - run: cmake --build build-docs --target docs
      - uses: actions/configure-pages@v5
        with:
          enablement: true
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build-docs/docs/html
      - name: Deploy API documentation
        id: deployment
        uses: actions/deploy-pages@v4
